name: Build Windows ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
         uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"  # 或者改为你项目使用的版本

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows ARM64
        run: flutter build windows --release --target-platform=windows-arm64

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: LocalSend-Windows-ARM64
          path: build/windows/arm64/runner/Release

